# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.create(name: '文学・評論')
Category.create(name: '人文・思想')
Category.create(name: '社会・政治･法律')
Category.create(name: 'ノンフィクション')
Category.create(name: '歴史・地理')
Category.create(name: 'ビジネス・経済')
Category.create(name: '投資・金融・会社経営')
Category.create(name: '科学・テクノロジー')
Category.create(name: '医学・薬学・看護学・歯科学')
Category.create(name: 'コンピュータ・IT')
Category.create(name: 'アート・建築・デザイン')
Category.create(name: '趣味・実用')
Category.create(name: 'スポーツ・アウトドア')
Category.create(name: '資格・検定・就職')
Category.create(name: '暮らし・健康・子育て')
Category.create(name: '旅行ガイド・マップ')
Category.create(name: '語学・辞事典・年鑑')
Category.create(name: '英語学習')
Category.create(name: '教育・学参・受験')
Category.create(name: '絵本・児童書')
Category.create(name: 'コミック・ラノベ・BL')
Category.create(name: 'ライトノベル')
Category.create(name: 'タレント写真集')
Category.create(name: 'ゲーム攻略本')
Category.create(name: 'エンターテイメント')
Category.create(name: '新書・文庫・ノベルス')
Category.create(name: '雑誌')
Category.create(name: '楽譜・スコア・音楽書')
Category.create(name: 'カレンダー・手帳')
Category.create(name: 'ポスター')
Category.create(name: '古本')
Category.create(name: '古書･希少本')
Category.create(name: 'アダルト')